import { Inter, Nunito } from 'next/font/google';
import { cookies } from "next/headers";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/lib/AuthContext";
import Login from "@/components/login/Login";
import "./globals.css";

const inter = Inter({
    subsets: ['latin'],
    display: 'swap', // Optional: Improves UX by swapping font after load
    variable: '--font-inter', // Optional: use as CSS variable
});

const nunito = Nunito({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-nunito',
});

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const baseURL = process.env.NEXT_PUBLIC_API_URL;
    const cookieStore = await cookies();
    const token = cookieStore.get("access_token")?.value;
    let user = null;

    if (token) {
        const res = await fetch(baseURL + 'check-auth/', {
            headers: {
                Cookie: `access_token=${token}`,
            },
            credentials: "include",
        });
        if (res.ok) {
            user = await res.json();
        }
    }

    return (
        <html lang="en">
            <body
                className={`${nunito.className} antialiased`}
            >
                <AuthProvider initialUser={user}>
                    {children}
                    <Login />
                    <Toaster position="bottom-center" />
                </AuthProvider>

            </body>
        </html>
    );
}
