import { DM_Sans, Open_Sans } from "next/font/google";
import "./globals.css";

export const dmSans = DM_Sans({
    subsets: ['latin'],
    weight: ['400', '500', '700'], // adjust as needed
    variable: '--font-dm-sans',
    display: 'swap',
});

export const openSans = Open_Sans({
    subsets: ['latin'],
    weight: ['300', '400', '600'],
    variable: '--font-open-sans',
    display: 'swap',
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    manifest: '/manifest.json',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${dmSans.variable} ${openSans.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
