import { DM_Sans, Open_Sans, Ubuntu } from "next/font/google";
import Login from "@/components/shared/Login";
import { LoginProvider } from "@/lib/LoginContext";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const dmSans = DM_Sans({
    subsets: ['latin'],
    weight: ['400', '500', '700'], // adjust as needed
    variable: '--font-dm-sans',
    display: 'swap',
});

export const openSans = Open_Sans({
    subsets: ['latin'],
    weight: ['300', '400', '600'],
    variable: '--font-open-sans',
    display: 'swap',
});

export const ubuntu = Ubuntu({
    subsets: ['latin'],
    weight: ['300', '400', '500', '700'],
    variable: '--font-ubuntu',
    display: 'swap',
});

export const metadata = {
    title: "Home | Affored",
    description: "Generated by create next app",
    manifest: '/manifest.json',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${ubuntu.variable} antialiased`}
            >
                <LoginProvider>
                    <Toaster position="bottom-center" />
                    {children}
                </LoginProvider>

            </body>
        </html>
    );
}
