export const metadata = {
    title: "User Profile",
    description: "Generated by create next app",
};

export default async function ProfileLayout({ children }) {


    return (
        <>
            {children}
        </>
    );
}