import { MyBizProvider } from "@/lib/MyBizContext";
import { cookies } from "next/headers";

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default async function MyBizLayout({ children, params  }) {
    const baseURL = process.env.NEXT_PUBLIC_API_URL;
    const cookieStore = await cookies();
    const token = cookieStore.get("access_token")?.value;
    let biz = null;
    params = await params;
    const id = params.id;

    if (token) {
        const res = await fetch(`${baseURL}my-business/${id}/`, {
            headers: {
                Cookie: `access_token=${token}`,
            },
            credentials: "include",
        });
        if (res.ok) {
            biz = await res.json();
        }
    }

    return (
            <MyBizProvider initialBiz={biz}>
                {children}
            </MyBizProvider>
    );
}
