export const metadata = {
    title: "My Business",
    description: "Generated by create next app",
};

export default async function MyBusinessLayout({ children }) {


    return (
        <>
            {children}
        </>
    );
}